### PR TITLE
Quicker Player Page Loading

### PR DESCRIPTION
**Pull request by DLu**
This patch fixes the issue of slow player pages in two ways. 

First, some of the goals stuff was slow because it was making a lot of changes to a very long string. This has been fixed with some intermediate strings and additional constants. In the future, we should probably come up with a cleverer way of displaying all the goals. 

Second, there is a new table called game_stats, which keeps a short record of each game (who won, where the winner sat). There is a function in game_stats.py that can be used to populate the table, however, at present, it is not set up to be run automatically. The DB values have already been filled in for all games played by hawaiian+shirts and rrenaud.

### CODE REVIEW

**Comment by mikemccllstr** [comment]
I will try to review and merge this in the next 24 hours... I've run out of steam for the day. But thanks!

**Comment by DLu** [comment]
Looking at the actual diff, some weird stuff got pulled that I didn't
intend. I'll try to resolve the issue tonight.

On Mon, Nov 26, 2012 at 12:44 AM, Mike McCallister <notifications@github.com

**Comment by mikemccllstr** [comment]
I see the recent activity here... Is this ready for me to review and merge?

**Comment by DLu** [comment]
Yes, I hope so!

**Comment by mikemccllstr** [comment]
I've pulled your latest into a branch in my repository called [DLu-master](https://github.com/mikemccllstr/dominionstats/tree/DLu-master). Before merging it to my main branch, I'd like to do a bit more work on the code so it can bulk-load the historical user data, and then keep the `game_stats` collection up-to-date as new gamelogs are imported.

**Comment by DLu** [comment]
Sounds like a good plan. I intended it to be written in a way that would
hopefully make that easy for you. Let me know how it goes.

On Thu, Dec 13, 2012 at 12:53 AM, Mike McCallister <notifications@github.com

**Comment by mikemccllstr** [comment]
Ok, main site is currently running the code on the DLu-Master branch in my repository, and all the games are parsed back through 2010-10-15. The player page definitely loads faster than before. Where there used to be timeouts (page for rrenaud), now it can run to completion. Can you take a look at the latest and let me know if you have any other concerns/ before I merge it into my master branch?

**Comment by DLu** [comment]
Looks good to me.
http://councilroom.mccllstr.com/player?player=WanderingWinder
This page loaded without TOO much trouble. There probably should be some
fancy CSS/HTML5 stuff to load it even quicker, but its servicable for now.

**Pull request merged**
